name: khinsider_sdk
description: SDK for video game musics from downloads.khinsider.com
version: 0.0.1
homepage: https://github.com/SebastianLiando/khinsider_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html: ^0.15.0
  http: ^0.13.3
  intl: ^0.17.0
  quiver: ^3.0.1

dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.4
  mockito: ^5.0.9
